# Form implementation generated from reading ui file 'd:\YXJ_Killer\untitled.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1290, 681)
        Form.setStyleSheet("background-color: #FFFFFF;")
        self.frame = QtWidgets.QFrame(parent=Form)
        self.frame.setGeometry(QtCore.QRect(0, 0, 690, 60))
        self.frame.setStyleSheet(
            "background: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(68, 244, 160, 255), stop:1 rgba(86,178,172, 255));"
        )
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.label_2 = QtWidgets.QLabel(parent=self.frame)
        self.label_2.setGeometry(QtCore.QRect(190, 10, 191, 41))
        self.label_2.setStyleSheet("background: none;\ncolor :#FFFFFF;")
        self.label_2.setObjectName("label_2")
        self.label = QtWidgets.QLabel(parent=self.frame)
        self.label.setGeometry(QtCore.QRect(60, 10, 191, 41))
        self.label.setStyleSheet("background: none;\ncolor :#FFFFFF;")
        self.label.setObjectName("label")
        self.label_6 = QtWidgets.QLabel(parent=self.frame)
        self.label_6.setGeometry(QtCore.QRect(10, 10, 40, 40))
        self.label_6.setStyleSheet("background: none;")
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap("assets/logo.png"))
        self.label_6.setScaledContents(True)
        self.label_6.setObjectName("label_6")
        self.pushButton_4 = QtWidgets.QPushButton(parent=self.frame)
        self.pushButton_4.setGeometry(QtCore.QRect(580, 16, 100, 32))
        self.pushButton_4.setStyleSheet(
            "QPushButton{\n"
            "background: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(77,116,212, 255), stop:1 rgba(77,153,212, 255));\n"
            "border: 1px solid #FFFFFF;\n"
            "color: #FFFFFF;\n"
            "border-radius: 10px;\n"
            "}\n"
            "QPushButton:hover{\n"
            "background: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(33,81,102, 255), stop:1 rgba(33,59,102, 255));\n"
            "color: #FFFFFF;\n"
            "border: 1px solid #FFFFFF;\n"
            "border-radius: 10px;\n"
            "}"
        )
        icon = QtGui.QIcon()
        icon.addPixmap(
            QtGui.QPixmap("assets/save.svg"),
            QtGui.QIcon.Mode.Normal,
            QtGui.QIcon.State.Off,
        )
        self.pushButton_4.setIcon(icon)
        self.pushButton_4.setIconSize(QtCore.QSize(24, 24))
        self.pushButton_4.setObjectName("pushButton_4")
        self.Setting = QtWidgets.QPushButton(parent=self.frame)
        self.Setting.setGeometry(QtCore.QRect(430, 0, 61, 61))
        self.Setting.setStyleSheet(
            "QPushButton{\n"
            "    border: 1px solid rgba(255, 255, 255, 120);\n"
            "    background: none;\n"
            "    border-width: 0px 0px 0px 0px;\n"
            "}\n"
            "QPushButton:hover{\n"
            "    border: 1px solid rgba(255, 255, 255, 60);\n"
            "    background: rgba(0, 0, 0, 10);\n"
            "    border-width: 0px 1px 0px 1px;\n"
            "}\n"
            "QPushButton:pressed{\n"
            "    border: 1px solid rgba(255, 255, 255, 120);\n"
            "    background: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(0, 0, 0, 0), stop:1 rgba(0, 0, 0, 60));\n"
            "    border-width: 0px 1px 0px 1px;\n"
            "}\n"
            "QPushButton:checked{\n"
            "    border: 1px solid rgba(255, 255, 255, 120);\n"
            "    background: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(0, 0, 0, 0), stop:1 rgba(0, 0, 0, 40));\n"
            "    border-width: 0px 1px 0px 1px;\n"
            "}"
        )
        self.Setting.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(
            QtGui.QPixmap("assets/setting.svg"),
            QtGui.QIcon.Mode.Normal,
            QtGui.QIcon.State.Off,
        )
        self.Setting.setIcon(icon1)
        self.Setting.setIconSize(QtCore.QSize(32, 32))
        self.Setting.setCheckable(True)
        self.Setting.setChecked(True)
        self.Setting.setAutoExclusive(True)
        self.Setting.setFlat(False)
        self.Setting.setObjectName("Setting")
        self.TextSetting = QtWidgets.QPushButton(parent=self.frame)
        self.TextSetting.setGeometry(QtCore.QRect(490, 0, 61, 61))
        self.TextSetting.setStyleSheet(
            "QPushButton{\n"
            "    border: 1px solid rgba(255, 255, 255, 120);\n"
            "    background: none;\n"
            "    border-width: 0px 0px 0px 0px;\n"
            "}\n"
            "QPushButton:hover{\n"
            "    border: 1px solid rgba(255, 255, 255, 60);\n"
            "    background: rgba(0, 0, 0, 10);\n"
            "    border-width: 0px 1px 0px 1px;\n"
            "}\n"
            "QPushButton:pressed{\n"
            "    border: 1px solid rgba(255, 255, 255, 120);\n"
            "    background: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(0, 0, 0, 0), stop:1 rgba(0, 0, 0, 60));\n"
            "    border-width: 0px 1px 0px 1px;\n"
            "}\n"
            "QPushButton:checked{\n"
            "    border: 1px solid rgba(255, 255, 255, 120);\n"
            "    background: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(0, 0, 0, 0), stop:1 rgba(0, 0, 0, 40));\n"
            "    border-width: 0px 1px 0px 1px;\n"
            "}"
        )
        self.TextSetting.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(
            QtGui.QPixmap("assets/text.svg"),
            QtGui.QIcon.Mode.Normal,
            QtGui.QIcon.State.Off,
        )
        self.TextSetting.setIcon(icon2)
        self.TextSetting.setIconSize(QtCore.QSize(32, 32))
        self.TextSetting.setCheckable(True)
        self.TextSetting.setAutoExclusive(True)
        self.TextSetting.setFlat(False)
        self.TextSetting.setObjectName("TextSetting")
        self.frame_2 = QtWidgets.QFrame(parent=Form)
        self.frame_2.setGeometry(QtCore.QRect(0, 390, 690, 41))
        self.frame_2.setStyleSheet(
            "background-color: #FFFAD6;\n"
            "border: 1px solid #D1D1D1;\n"
            "border-width: 1px 0px 0px 0px;\n"
            ""
        )
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label_3 = QtWidgets.QLabel(parent=self.frame_2)
        self.label_3.setGeometry(QtCore.QRect(10, 10, 681, 21))
        self.label_3.setStyleSheet("background: none;\ncolor :#000000;\nborder: none;")
        self.label_3.setObjectName("label_3")
        self.label_5 = QtWidgets.QLabel(parent=Form)
        self.label_5.setGeometry(QtCore.QRect(20, 140, 181, 171))
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap("assets/decoration.png"))
        self.label_5.setScaledContents(False)
        self.label_5.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.label_7 = QtWidgets.QLabel(parent=Form)
        self.label_7.setGeometry(QtCore.QRect(40, 80, 211, 51))
        self.label_7.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.label_7.setTextFormat(QtCore.Qt.TextFormat.RichText)
        self.label_7.setAlignment(
            QtCore.Qt.AlignmentFlag.AlignLeading
            | QtCore.Qt.AlignmentFlag.AlignLeft
            | QtCore.Qt.AlignmentFlag.AlignVCenter
        )
        self.label_7.setObjectName("label_7")
        self.pushButton = QtWidgets.QPushButton(parent=Form)
        self.pushButton.setGeometry(QtCore.QRect(390, 350, 140, 31))
        self.pushButton.setStyleSheet(
            "QPushButton{\n"
            "    background-color: #00CA72;\n"
            "    color: #FFFFFF;\n"
            "    border-radius: 6px;\n"
            "}\n"
            "QPushButton:hover{\n"
            "    background-color: #00BF6C;\n"
            "    color: #FFFFFF;\n"
            "    border-radius: 6px;\n"
            "}\n"
            "QPushButton:pressed{\n"
            "    background-color: #007B45;\n"
            "    color: #FFFFFF;\n"
            "    border-radius: 6px;\n"
            "}"
        )
        icon3 = QtGui.QIcon()
        icon3.addPixmap(
            QtGui.QPixmap("assets/kill.svg"),
            QtGui.QIcon.Mode.Normal,
            QtGui.QIcon.State.Off,
        )
        self.pushButton.setIcon(icon3)
        self.pushButton.setIconSize(QtCore.QSize(24, 24))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(parent=Form)
        self.pushButton_2.setGeometry(QtCore.QRect(240, 350, 140, 31))
        self.pushButton_2.setStyleSheet(
            "QPushButton{\n"
            "    background-color: #00CA72;\n"
            "    color: #FFFFFF;\n"
            "    border-radius: 6px;\n"
            "}\n"
            "QPushButton:hover{\n"
            "    background-color: #00BF6C;\n"
            "    color: #FFFFFF;\n"
            "    border-radius: 6px;\n"
            "}\n"
            "QPushButton:pressed{\n"
            "    background-color: #007B45;\n"
            "    color: #FFFFFF;\n"
            "    border-radius: 6px;\n"
            "}"
        )
        icon4 = QtGui.QIcon()
        icon4.addPixmap(
            QtGui.QPixmap("assets/dismiss.svg"),
            QtGui.QIcon.Mode.Normal,
            QtGui.QIcon.State.Off,
        )
        self.pushButton_2.setIcon(icon4)
        self.pushButton_2.setIconSize(QtCore.QSize(24, 24))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(parent=Form)
        self.pushButton_3.setGeometry(QtCore.QRect(540, 350, 140, 31))
        self.pushButton_3.setStyleSheet(
            "QPushButton{\n"
            "    background-color: #00CA72;\n"
            "    color: #FFFFFF;\n"
            "    border-radius: 6px;\n"
            "}\n"
            "QPushButton:hover{\n"
            "    background-color: #00BF6C;\n"
            "    color: #FFFFFF;\n"
            "    border-radius: 6px;\n"
            "}\n"
            "QPushButton:pressed{\n"
            "    background-color: #007B45;\n"
            "    color: #FFFFFF;\n"
            "    border-radius: 6px;\n"
            "}"
        )
        icon5 = QtGui.QIcon()
        icon5.addPixmap(
            QtGui.QPixmap("assets/debug.svg"),
            QtGui.QIcon.Mode.Normal,
            QtGui.QIcon.State.Off,
        )
        self.pushButton_3.setIcon(icon5)
        self.pushButton_3.setIconSize(QtCore.QSize(24, 24))
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayoutWidget = QtWidgets.QWidget(parent=Form)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(250, 80, 431, 221))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.NormalSettingWindow = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.NormalSettingWindow.setContentsMargins(0, 0, 0, 0)
        self.NormalSettingWindow.setObjectName("NormalSettingWindow")
        self.checkBox_6 = QtWidgets.QCheckBox(parent=self.verticalLayoutWidget)
        self.checkBox_6.setStyleSheet("background: none;")
        self.checkBox_6.setChecked(True)
        self.checkBox_6.setObjectName("checkBox_6")
        self.NormalSettingWindow.addWidget(self.checkBox_6)
        self.checkBox_8 = QtWidgets.QCheckBox(parent=self.verticalLayoutWidget)
        self.checkBox_8.setStyleSheet("background: none;")
        self.checkBox_8.setChecked(True)
        self.checkBox_8.setObjectName("checkBox_8")
        self.NormalSettingWindow.addWidget(self.checkBox_8)
        self.checkBox_7 = QtWidgets.QCheckBox(parent=self.verticalLayoutWidget)
        self.checkBox_7.setStyleSheet("background: none;")
        self.checkBox_7.setChecked(True)
        self.checkBox_7.setObjectName("checkBox_7")
        self.NormalSettingWindow.addWidget(self.checkBox_7)
        self.checkBox_11 = QtWidgets.QCheckBox(parent=self.verticalLayoutWidget)
        self.checkBox_11.setStyleSheet("background: none;")
        self.checkBox_11.setChecked(False)
        self.checkBox_11.setObjectName("checkBox_11")
        self.NormalSettingWindow.addWidget(self.checkBox_11)
        self.checkBox_5 = QtWidgets.QCheckBox(parent=self.verticalLayoutWidget)
        self.checkBox_5.setStyleSheet("background: none;")
        self.checkBox_5.setChecked(True)
        self.checkBox_5.setObjectName("checkBox_5")
        self.NormalSettingWindow.addWidget(self.checkBox_5)
        self.frame_3 = QtWidgets.QFrame(parent=self.verticalLayoutWidget)
        self.frame_3.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_3.setObjectName("frame_3")
        self.checkBox_9 = QtWidgets.QCheckBox(parent=self.frame_3)
        self.checkBox_9.setGeometry(QtCore.QRect(20, 10, 221, 20))
        self.checkBox_9.setStyleSheet("color: #333333;")
        self.checkBox_9.setChecked(True)
        self.checkBox_9.setObjectName("checkBox_9")
        self.checkBox_10 = QtWidgets.QCheckBox(parent=self.frame_3)
        self.checkBox_10.setEnabled(False)
        self.checkBox_10.setGeometry(QtCore.QRect(20, 40, 221, 20))
        self.checkBox_10.setStyleSheet("color: #666666;")
        self.checkBox_10.setCheckable(True)
        self.checkBox_10.setChecked(False)
        self.checkBox_10.setObjectName("checkBox_10")
        self.radioButton = QtWidgets.QRadioButton(parent=self.frame_3)
        self.radioButton.setGeometry(QtCore.QRect(20, 70, 51, 20))
        self.radioButton.setChecked(True)
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(parent=self.frame_3)
        self.radioButton_2.setGeometry(QtCore.QRect(60, 70, 51, 20))
        self.radioButton_2.setChecked(False)
        self.radioButton_2.setObjectName("radioButton_2")
        self.radioButton_3 = QtWidgets.QRadioButton(parent=self.frame_3)
        self.radioButton_3.setEnabled(False)
        self.radioButton_3.setGeometry(QtCore.QRect(100, 70, 51, 20))
        self.radioButton_3.setChecked(False)
        self.radioButton_3.setObjectName("radioButton_3")
        self.lineEdit = QtWidgets.QLineEdit(parent=self.frame_3)
        self.lineEdit.setGeometry(QtCore.QRect(130, 10, 61, 22))
        self.lineEdit.setStyleSheet(
            "QLineEdit{\n"
            "    border: 1px solid #DDDDDD;\n"
            "    border-radius: 5px;\n"
            "}\n"
            "QLineEdit:hover{\n"
            "    border: 1px solid #4DD4A6;\n"
            "    border-radius: 5px;\n"
            "}"
        )
        self.lineEdit.setInputMask("")
        self.lineEdit.setDragEnabled(True)
        self.lineEdit.setClearButtonEnabled(True)
        self.lineEdit.setObjectName("lineEdit")
        self.NormalSettingWindow.addWidget(self.frame_3)
        self.frame_4 = QtWidgets.QFrame(parent=Form)
        self.frame_4.setGeometry(QtCore.QRect(250, 310, 429, 38))
        self.frame_4.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_4.setObjectName("frame_4")
        self.lineEdit_2 = QtWidgets.QLineEdit(parent=self.frame_4)
        self.lineEdit_2.setGeometry(QtCore.QRect(110, 10, 61, 22))
        self.lineEdit_2.setStyleSheet(
            "QLineEdit{\n"
            "    border: 1px solid #DDDDDD;\n"
            "    border-radius: 5px;\n"
            "}\n"
            "QLineEdit:hover{\n"
            "    border: 1px solid #4DD4A6;\n"
            "    border-radius: 5px;\n"
            "}"
        )
        self.lineEdit_2.setInputMask("")
        self.lineEdit_2.setDragEnabled(True)
        self.lineEdit_2.setClearButtonEnabled(True)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_4 = QtWidgets.QLabel(parent=self.frame_4)
        self.label_4.setGeometry(QtCore.QRect(0, 10, 101, 16))
        self.label_4.setObjectName("label_4")
        self.TextEditWindow = QtWidgets.QFrame(parent=Form)
        self.TextEditWindow.setGeometry(QtCore.QRect(250, 80, 440, 264))
        self.TextEditWindow.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.TextEditWindow.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.TextEditWindow.setObjectName("TextEditWindow")
        self.label_8 = QtWidgets.QLabel(parent=self.TextEditWindow)
        self.label_8.setGeometry(QtCore.QRect(0, 10, 150, 20))
        self.label_8.setObjectName("label_8")
        self.lineEdit_3 = QtWidgets.QLineEdit(parent=self.TextEditWindow)
        self.lineEdit_3.setGeometry(QtCore.QRect(120, 10, 190, 20))
        self.lineEdit_3.setStyleSheet(
            "QLineEdit{\n"
            "    border: 1px solid #DDDDDD;\n"
            "    border-radius: 5px;\n"
            "}\n"
            "QLineEdit:hover{\n"
            "    border: 1px solid #4DD4A6;\n"
            "    border-radius: 5px;\n"
            "}"
        )
        self.lineEdit_3.setInputMask("")
        self.lineEdit_3.setFrame(True)
        self.lineEdit_3.setEchoMode(QtWidgets.QLineEdit.EchoMode.Normal)
        self.lineEdit_3.setDragEnabled(True)
        self.lineEdit_3.setClearButtonEnabled(True)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.label_10 = QtWidgets.QLabel(parent=self.TextEditWindow)
        self.label_10.setGeometry(QtCore.QRect(0, 40, 150, 20))
        self.label_10.setObjectName("label_10")
        self.lineEdit_4 = QtWidgets.QLineEdit(parent=self.TextEditWindow)
        self.lineEdit_4.setGeometry(QtCore.QRect(120, 40, 190, 20))
        self.lineEdit_4.setStyleSheet(
            "QLineEdit{\n"
            "    border: 1px solid #DDDDDD;\n"
            "    border-radius: 5px;\n"
            "}\n"
            "QLineEdit:hover{\n"
            "    border: 1px solid #4DD4A6;\n"
            "    border-radius: 5px;\n"
            "}"
        )
        self.lineEdit_4.setInputMask("")
        self.lineEdit_4.setDragEnabled(True)
        self.lineEdit_4.setClearButtonEnabled(True)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.label_11 = QtWidgets.QLabel(parent=self.TextEditWindow)
        self.label_11.setGeometry(QtCore.QRect(0, 70, 150, 20))
        self.label_11.setObjectName("label_11")
        self.lineEdit_6 = QtWidgets.QLineEdit(parent=self.TextEditWindow)
        self.lineEdit_6.setGeometry(QtCore.QRect(120, 70, 190, 20))
        self.lineEdit_6.setStyleSheet(
            "QLineEdit{\n"
            "    border: 1px solid #DDDDDD;\n"
            "    border-radius: 5px;\n"
            "}\n"
            "QLineEdit:hover{\n"
            "    border: 1px solid #4DD4A6;\n"
            "    border-radius: 5px;\n"
            "}"
        )
        self.lineEdit_6.setInputMask("")
        self.lineEdit_6.setDragEnabled(True)
        self.lineEdit_6.setClearButtonEnabled(True)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.label_12 = QtWidgets.QLabel(parent=self.TextEditWindow)
        self.label_12.setGeometry(QtCore.QRect(0, 100, 150, 20))
        self.label_12.setObjectName("label_12")
        self.lineEdit_7 = QtWidgets.QLineEdit(parent=self.TextEditWindow)
        self.lineEdit_7.setGeometry(QtCore.QRect(120, 100, 190, 20))
        self.lineEdit_7.setStyleSheet(
            "QLineEdit{\n"
            "    border: 1px solid #DDDDDD;\n"
            "    border-radius: 5px;\n"
            "}\n"
            "QLineEdit:hover{\n"
            "    border: 1px solid #4DD4A6;\n"
            "    border-radius: 5px;\n"
            "}"
        )
        self.lineEdit_7.setInputMask("")
        self.lineEdit_7.setDragEnabled(True)
        self.lineEdit_7.setClearButtonEnabled(True)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.label_13 = QtWidgets.QLabel(parent=self.TextEditWindow)
        self.label_13.setGeometry(QtCore.QRect(0, 130, 150, 20))
        self.label_13.setObjectName("label_13")
        self.lineEdit_8 = QtWidgets.QLineEdit(parent=self.TextEditWindow)
        self.lineEdit_8.setGeometry(QtCore.QRect(120, 130, 190, 20))
        self.lineEdit_8.setStyleSheet(
            "QLineEdit{\n"
            "    border: 1px solid #DDDDDD;\n"
            "    border-radius: 5px;\n"
            "}\n"
            "QLineEdit:hover{\n"
            "    border: 1px solid #4DD4A6;\n"
            "    border-radius: 5px;\n"
            "}"
        )
        self.lineEdit_8.setInputMask("")
        self.lineEdit_8.setDragEnabled(True)
        self.lineEdit_8.setClearButtonEnabled(True)
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.label_14 = QtWidgets.QLabel(parent=self.TextEditWindow)
        self.label_14.setGeometry(QtCore.QRect(0, 160, 150, 20))
        self.label_14.setObjectName("label_14")
        self.lineEdit_9 = QtWidgets.QLineEdit(parent=self.TextEditWindow)
        self.lineEdit_9.setGeometry(QtCore.QRect(120, 160, 190, 20))
        self.lineEdit_9.setStyleSheet(
            "QLineEdit{\n"
            "    border: 1px solid #DDDDDD;\n"
            "    border-radius: 5px;\n"
            "}\n"
            "QLineEdit:hover{\n"
            "    border: 1px solid #4DD4A6;\n"
            "    border-radius: 5px;\n"
            "}"
        )
        self.lineEdit_9.setInputMask("")
        self.lineEdit_9.setDragEnabled(True)
        self.lineEdit_9.setClearButtonEnabled(True)
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.label_15 = QtWidgets.QLabel(parent=self.TextEditWindow)
        self.label_15.setGeometry(QtCore.QRect(0, 190, 150, 20))
        self.label_15.setObjectName("label_15")
        self.lineEdit_10 = QtWidgets.QLineEdit(parent=self.TextEditWindow)
        self.lineEdit_10.setGeometry(QtCore.QRect(120, 190, 190, 20))
        self.lineEdit_10.setStyleSheet(
            "QLineEdit{\n"
            "    border: 1px solid #DDDDDD;\n"
            "    border-radius: 5px;\n"
            "}\n"
            "QLineEdit:hover{\n"
            "    border: 1px solid #4DD4A6;\n"
            "    border-radius: 5px;\n"
            "}"
        )
        self.lineEdit_10.setInputMask("")
        self.lineEdit_10.setDragEnabled(True)
        self.lineEdit_10.setClearButtonEnabled(True)
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.frame_5 = QtWidgets.QFrame(parent=Form)
        self.frame_5.setGeometry(QtCore.QRect(110, 80, 451, 261))
        self.frame_5.setStyleSheet(
            "background-color: rgba(255, 255, 255, 220);\n"
            "border: 1px solid #DDDDDD;\n"
            "border-radius: 5px;"
        )
        self.frame_5.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_5.setObjectName("frame_5")
        self.checkBox = QtWidgets.QCheckBox(parent=self.frame_5)
        self.checkBox.setGeometry(QtCore.QRect(10, 60, 211, 31))
        self.checkBox.setStyleSheet(
            "background: none;\n"
            "border: none;\n"
            "QCheckBox::indicator:unchecked {\n"
            '    image: url("assets/unchecked.png");    \n'
            "    background: none;\n"
            "    border: none;\n"
            "}\n"
            "QCheckBox::indicator:checked {\n"
            '    image: url("assets/checked.png");\n'
            "    background: none;\n"
            "    border: none;\n"
            "}"
        )
        self.checkBox.setChecked(False)
        self.checkBox.setTristate(False)
        self.checkBox.setObjectName("checkBox")
        self.label_16 = QtWidgets.QLabel(parent=self.frame_5)
        self.label_16.setGeometry(QtCore.QRect(10, 40, 431, 21))
        self.label_16.setStyleSheet("background: none;\nborder: none;")
        self.label_16.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(parent=self.frame_5)
        self.label_17.setGeometry(QtCore.QRect(10, 10, 281, 31))
        self.label_17.setStyleSheet("background: none;\nborder: none;")
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(parent=self.frame_5)
        self.label_18.setGeometry(QtCore.QRect(10, 140, 281, 31))
        self.label_18.setStyleSheet("background: none;\nborder: none;")
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(parent=self.frame_5)
        self.label_19.setGeometry(QtCore.QRect(10, 180, 431, 71))
        self.label_19.setStyleSheet("background: none;\nborder: none;")
        self.label_19.setObjectName("label_19")
        self.TextSetting_2 = QtWidgets.QPushButton(parent=self.frame_5)
        self.TextSetting_2.setGeometry(QtCore.QRect(410, 10, 31, 31))
        self.TextSetting_2.setStyleSheet("background: none;\nborder: none;")
        self.TextSetting_2.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(
            QtGui.QPixmap("assets/close.svg"),
            QtGui.QIcon.Mode.Normal,
            QtGui.QIcon.State.Off,
        )
        self.TextSetting_2.setIcon(icon6)
        self.TextSetting_2.setIconSize(QtCore.QSize(24, 24))
        self.TextSetting_2.setCheckable(True)
        self.TextSetting_2.setAutoExclusive(True)
        self.TextSetting_2.setFlat(False)
        self.TextSetting_2.setObjectName("TextSetting_2")
        self.pushButton_5 = QtWidgets.QPushButton(parent=self.frame_5)
        self.pushButton_5.setGeometry(QtCore.QRect(10, 90, 111, 31))
        self.pushButton_5.setStyleSheet(
            "QPushButton{\n"
            "    background-color: #00CA72;\n"
            "    color: #FFFFFF;\n"
            "    border: none;\n"
            "    border-radius: 6px;\n"
            "}\n"
            "QPushButton:hover{\n"
            "    background-color: #00BF6C;\n"
            "    color: #FFFFFF;\n"
            "    border: none;\n"
            "    border-radius: 6px;\n"
            "}\n"
            "QPushButton:pressed{\n"
            "    background-color: #007B45;\n"
            "    color: #FFFFFF;\n"
            "    border: none;\n"
            "    border-radius: 6px;\n"
            "}"
        )
        icon7 = QtGui.QIcon()
        icon7.addPixmap(
            QtGui.QPixmap("assets/edit.svg"),
            QtGui.QIcon.Mode.Normal,
            QtGui.QIcon.State.Off,
        )
        self.pushButton_5.setIcon(icon7)
        self.pushButton_5.setIconSize(QtCore.QSize(24, 24))
        self.pushButton_5.setObjectName("pushButton_5")
        self.label_9 = QtWidgets.QLabel(parent=Form)
        self.label_9.setGeometry(QtCore.QRect(0, 60, 690, 16))
        self.label_9.setText("")
        self.label_9.setPixmap(QtGui.QPixmap("assets/bar.png"))
        self.label_9.setScaledContents(True)
        self.label_9.setObjectName("label_9")
        self.frame_6 = QtWidgets.QFrame(parent=Form)
        self.frame_6.setGeometry(QtCore.QRect(220, 80, 231, 261))
        self.frame_6.setStyleSheet(
            "background-color: rgba(255, 255, 255, 220);\n"
            "border: 1px solid #DDDDDD;\n"
            "border-radius: 5px;"
        )
        self.frame_6.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_6.setObjectName("frame_6")
        self.label_21 = QtWidgets.QLabel(parent=self.frame_6)
        self.label_21.setGeometry(QtCore.QRect(10, 10, 281, 31))
        self.label_21.setStyleSheet("background: none;\nborder: none;")
        self.label_21.setObjectName("label_21")
        self.TextSetting_3 = QtWidgets.QPushButton(parent=self.frame_6)
        self.TextSetting_3.setGeometry(QtCore.QRect(200, 10, 31, 31))
        self.TextSetting_3.setStyleSheet("background: none;\nborder: none;")
        self.TextSetting_3.setText("")
        self.TextSetting_3.setIcon(icon6)
        self.TextSetting_3.setIconSize(QtCore.QSize(24, 24))
        self.TextSetting_3.setCheckable(True)
        self.TextSetting_3.setAutoExclusive(True)
        self.TextSetting_3.setFlat(False)
        self.TextSetting_3.setObjectName("TextSetting_3")
        self.label_20 = QtWidgets.QLabel(parent=self.frame_6)
        self.label_20.setGeometry(QtCore.QRect(10, 40, 211, 61))
        self.label_20.setStyleSheet("background: none;\nborder: none;")
        self.label_20.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.label_20.setScaledContents(False)
        self.label_20.setWordWrap(True)
        self.label_20.setObjectName("label_20")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(parent=self.frame_6)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(20, 100, 81, 151))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.timeEdit = QtWidgets.QTimeEdit(parent=self.verticalLayoutWidget_2)
        self.timeEdit.setStyleSheet(
            "QtimeEdit{\n"
            "    border: 1px solid #DDDDDD;\n"
            "    border-radius: 5px;\n"
            "}\n"
            "QtimeEdit:hover{\n"
            "    border: 1px solid #4DD4A6;\n"
            "    border-radius: 5px;\n"
            "}"
        )
        self.timeEdit.setWrapping(False)
        self.timeEdit.setFrame(True)
        self.timeEdit.setButtonSymbols(
            QtWidgets.QAbstractSpinBox.ButtonSymbols.NoButtons
        )
        self.timeEdit.setProperty("showGroupSeparator", False)
        self.timeEdit.setCalendarPopup(False)
        self.timeEdit.setObjectName("timeEdit")
        self.verticalLayout.addWidget(self.timeEdit)
        self.timeEdit_2 = QtWidgets.QTimeEdit(parent=self.verticalLayoutWidget_2)
        self.timeEdit_2.setStyleSheet(
            "QtimeEdit{\n"
            "    border: 1px solid #DDDDDD;\n"
            "    border-radius: 5px;\n"
            "}\n"
            "QtimeEdit:hover{\n"
            "    border: 1px solid #4DD4A6;\n"
            "    border-radius: 5px;\n"
            "}"
        )
        self.timeEdit_2.setWrapping(False)
        self.timeEdit_2.setFrame(True)
        self.timeEdit_2.setButtonSymbols(
            QtWidgets.QAbstractSpinBox.ButtonSymbols.NoButtons
        )
        self.timeEdit_2.setProperty("showGroupSeparator", False)
        self.timeEdit_2.setCalendarPopup(False)
        self.timeEdit_2.setObjectName("timeEdit_2")
        self.verticalLayout.addWidget(self.timeEdit_2)
        self.timeEdit_3 = QtWidgets.QTimeEdit(parent=self.verticalLayoutWidget_2)
        self.timeEdit_3.setStyleSheet(
            "QtimeEdit{\n"
            "    border: 1px solid #DDDDDD;\n"
            "    border-radius: 5px;\n"
            "}\n"
            "QtimeEdit:hover{\n"
            "    border: 1px solid #4DD4A6;\n"
            "    border-radius: 5px;\n"
            "}"
        )
        self.timeEdit_3.setWrapping(False)
        self.timeEdit_3.setFrame(True)
        self.timeEdit_3.setButtonSymbols(
            QtWidgets.QAbstractSpinBox.ButtonSymbols.NoButtons
        )
        self.timeEdit_3.setProperty("showGroupSeparator", False)
        self.timeEdit_3.setCalendarPopup(False)
        self.timeEdit_3.setObjectName("timeEdit_3")
        self.verticalLayout.addWidget(self.timeEdit_3)
        self.timeEdit_4 = QtWidgets.QTimeEdit(parent=self.verticalLayoutWidget_2)
        self.timeEdit_4.setStyleSheet(
            "QtimeEdit{\n"
            "    border: 1px solid #DDDDDD;\n"
            "    border-radius: 5px;\n"
            "}\n"
            "QtimeEdit:hover{\n"
            "    border: 1px solid #4DD4A6;\n"
            "    border-radius: 5px;\n"
            "}"
        )
        self.timeEdit_4.setWrapping(False)
        self.timeEdit_4.setFrame(True)
        self.timeEdit_4.setButtonSymbols(
            QtWidgets.QAbstractSpinBox.ButtonSymbols.NoButtons
        )
        self.timeEdit_4.setProperty("showGroupSeparator", False)
        self.timeEdit_4.setCalendarPopup(False)
        self.timeEdit_4.setObjectName("timeEdit_4")
        self.verticalLayout.addWidget(self.timeEdit_4)
        self.timeEdit_5 = QtWidgets.QTimeEdit(parent=self.verticalLayoutWidget_2)
        self.timeEdit_5.setStyleSheet(
            "QtimeEdit{\n"
            "    border: 1px solid #DDDDDD;\n"
            "    border-radius: 5px;\n"
            "}\n"
            "QtimeEdit:hover{\n"
            "    border: 1px solid #4DD4A6;\n"
            "    border-radius: 5px;\n"
            "}"
        )
        self.timeEdit_5.setWrapping(False)
        self.timeEdit_5.setFrame(True)
        self.timeEdit_5.setButtonSymbols(
            QtWidgets.QAbstractSpinBox.ButtonSymbols.NoButtons
        )
        self.timeEdit_5.setProperty("showGroupSeparator", False)
        self.timeEdit_5.setCalendarPopup(False)
        self.timeEdit_5.setObjectName("timeEdit_5")
        self.verticalLayout.addWidget(self.timeEdit_5)
        self.timeEdit_6 = QtWidgets.QTimeEdit(parent=self.verticalLayoutWidget_2)
        self.timeEdit_6.setStyleSheet(
            "QtimeEdit{\n"
            "    border: 1px solid #DDDDDD;\n"
            "    border-radius: 5px;\n"
            "}\n"
            "QtimeEdit:hover{\n"
            "    border: 1px solid #4DD4A6;\n"
            "    border-radius: 5px;\n"
            "}"
        )
        self.timeEdit_6.setWrapping(False)
        self.timeEdit_6.setFrame(True)
        self.timeEdit_6.setButtonSymbols(
            QtWidgets.QAbstractSpinBox.ButtonSymbols.NoButtons
        )
        self.timeEdit_6.setProperty("showGroupSeparator", False)
        self.timeEdit_6.setCalendarPopup(False)
        self.timeEdit_6.setObjectName("timeEdit_6")
        self.verticalLayout.addWidget(self.timeEdit_6)
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(parent=self.frame_6)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(120, 100, 81, 151))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.timeEdit_7 = QtWidgets.QTimeEdit(parent=self.verticalLayoutWidget_3)
        self.timeEdit_7.setStyleSheet(
            "QtimeEdit{\n"
            "    border: 1px solid #DDDDDD;\n"
            "    border-radius: 5px;\n"
            "}\n"
            "QtimeEdit:hover{\n"
            "    border: 1px solid #4DD4A6;\n"
            "    border-radius: 5px;\n"
            "}"
        )
        self.timeEdit_7.setWrapping(False)
        self.timeEdit_7.setFrame(True)
        self.timeEdit_7.setButtonSymbols(
            QtWidgets.QAbstractSpinBox.ButtonSymbols.NoButtons
        )
        self.timeEdit_7.setProperty("showGroupSeparator", False)
        self.timeEdit_7.setCalendarPopup(False)
        self.timeEdit_7.setObjectName("timeEdit_7")
        self.verticalLayout_2.addWidget(self.timeEdit_7)
        self.timeEdit_8 = QtWidgets.QTimeEdit(parent=self.verticalLayoutWidget_3)
        self.timeEdit_8.setStyleSheet(
            "QtimeEdit{\n"
            "    border: 1px solid #DDDDDD;\n"
            "    border-radius: 5px;\n"
            "}\n"
            "QtimeEdit:hover{\n"
            "    border: 1px solid #4DD4A6;\n"
            "    border-radius: 5px;\n"
            "}"
        )
        self.timeEdit_8.setWrapping(False)
        self.timeEdit_8.setFrame(True)
        self.timeEdit_8.setButtonSymbols(
            QtWidgets.QAbstractSpinBox.ButtonSymbols.NoButtons
        )
        self.timeEdit_8.setProperty("showGroupSeparator", False)
        self.timeEdit_8.setCalendarPopup(False)
        self.timeEdit_8.setObjectName("timeEdit_8")
        self.verticalLayout_2.addWidget(self.timeEdit_8)
        self.timeEdit_9 = QtWidgets.QTimeEdit(parent=self.verticalLayoutWidget_3)
        self.timeEdit_9.setStyleSheet(
            "QtimeEdit{\n"
            "    border: 1px solid #DDDDDD;\n"
            "    border-radius: 5px;\n"
            "}\n"
            "QtimeEdit:hover{\n"
            "    border: 1px solid #4DD4A6;\n"
            "    border-radius: 5px;\n"
            "}"
        )
        self.timeEdit_9.setWrapping(False)
        self.timeEdit_9.setFrame(True)
        self.timeEdit_9.setButtonSymbols(
            QtWidgets.QAbstractSpinBox.ButtonSymbols.NoButtons
        )
        self.timeEdit_9.setProperty("showGroupSeparator", False)
        self.timeEdit_9.setCalendarPopup(False)
        self.timeEdit_9.setObjectName("timeEdit_9")
        self.verticalLayout_2.addWidget(self.timeEdit_9)
        self.timeEdit_10 = QtWidgets.QTimeEdit(parent=self.verticalLayoutWidget_3)
        self.timeEdit_10.setStyleSheet(
            "QtimeEdit{\n"
            "    border: 1px solid #DDDDDD;\n"
            "    border-radius: 5px;\n"
            "}\n"
            "QtimeEdit:hover{\n"
            "    border: 1px solid #4DD4A6;\n"
            "    border-radius: 5px;\n"
            "}"
        )
        self.timeEdit_10.setWrapping(False)
        self.timeEdit_10.setFrame(True)
        self.timeEdit_10.setButtonSymbols(
            QtWidgets.QAbstractSpinBox.ButtonSymbols.NoButtons
        )
        self.timeEdit_10.setProperty("showGroupSeparator", False)
        self.timeEdit_10.setCalendarPopup(False)
        self.timeEdit_10.setObjectName("timeEdit_10")
        self.verticalLayout_2.addWidget(self.timeEdit_10)
        self.timeEdit_11 = QtWidgets.QTimeEdit(parent=self.verticalLayoutWidget_3)
        self.timeEdit_11.setStyleSheet(
            "QtimeEdit{\n"
            "    border: 1px solid #DDDDDD;\n"
            "    border-radius: 5px;\n"
            "}\n"
            "QtimeEdit:hover{\n"
            "    border: 1px solid #4DD4A6;\n"
            "    border-radius: 5px;\n"
            "}"
        )
        self.timeEdit_11.setWrapping(False)
        self.timeEdit_11.setFrame(True)
        self.timeEdit_11.setButtonSymbols(
            QtWidgets.QAbstractSpinBox.ButtonSymbols.NoButtons
        )
        self.timeEdit_11.setProperty("showGroupSeparator", False)
        self.timeEdit_11.setCalendarPopup(False)
        self.timeEdit_11.setObjectName("timeEdit_11")
        self.verticalLayout_2.addWidget(self.timeEdit_11)
        self.timeEdit_12 = QtWidgets.QTimeEdit(parent=self.verticalLayoutWidget_3)
        self.timeEdit_12.setStyleSheet(
            "QtimeEdit{\n"
            "    border: 1px solid #DDDDDD;\n"
            "    border-radius: 5px;\n"
            "}\n"
            "QtimeEdit:hover{\n"
            "    border: 1px solid #4DD4A6;\n"
            "    border-radius: 5px;\n"
            "}"
        )
        self.timeEdit_12.setWrapping(False)
        self.timeEdit_12.setFrame(True)
        self.timeEdit_12.setButtonSymbols(
            QtWidgets.QAbstractSpinBox.ButtonSymbols.NoButtons
        )
        self.timeEdit_12.setProperty("showGroupSeparator", False)
        self.timeEdit_12.setCalendarPopup(False)
        self.timeEdit_12.setObjectName("timeEdit_12")
        self.verticalLayout_2.addWidget(self.timeEdit_12)
        self.toast = QtWidgets.QFrame(parent=Form)
        self.toast.setGeometry(QtCore.QRect(260, 50, 160, 40))
        self.toast.setStyleSheet(
            "background-color: rgba(0, 0, 0, 180);\n"
            "color: #FFFFFF;\n"
            "border-radius: 20px;"
        )
        self.toast.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.toast.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.toast.setObjectName("toast")
        self.label_22 = QtWidgets.QLabel(parent=self.toast)
        self.label_22.setGeometry(QtCore.QRect(20, 8, 24, 24))
        self.label_22.setStyleSheet("background:none;")
        self.label_22.setText("")
        self.label_22.setPixmap(QtGui.QPixmap("assets/saveok.png"))
        self.label_22.setScaledContents(True)
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(parent=self.toast)
        self.label_23.setGeometry(QtCore.QRect(60, 10, 81, 21))
        self.label_23.setStyleSheet("background: none;")
        self.label_23.setObjectName("label_23")
        self.frame.raise_()
        self.frame_2.raise_()
        self.label_5.raise_()
        self.label_7.raise_()
        self.pushButton.raise_()
        self.pushButton_2.raise_()
        self.pushButton_3.raise_()
        self.verticalLayoutWidget.raise_()
        self.frame_4.raise_()
        self.TextEditWindow.raise_()
        self.label_9.raise_()
        self.frame_5.raise_()
        self.frame_6.raise_()
        self.toast.raise_()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "360拖堂卫士"))
        self.label_2.setText(
            _translate(
                "Form",
                '<html><head/><body><p><span style=" font-size:10pt;">为您的课堂保驾护航</span></p></body></html>',
            )
        )
        self.label.setText(
            _translate(
                "Form",
                '<html><head/><body><p><span style=" font-size:16pt; font-weight:700;">360拖堂卫士</span></p></body></html>',
            )
        )
        self.pushButton_4.setText(_translate("Form", "保存修改"))
        self.label_3.setText(
            _translate(
                "Form",
                '<html><head/><body><p><span style=" font-size:10pt;">若让ClassIsland等时间表程序接管下课事件，下课时间编辑器将不再可用&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;时间表触发周期：60s</span></p></body></html>',
            )
        )
        self.label_7.setText(
            _translate(
                "Form",
                '<html><head/><body><p><span style=" font-size:16pt; font-weight:700;">拖堂防护已开启</span></p></body></html>',
            )
        )
        self.pushButton.setText(_translate("Form", "设置要查杀的程序"))
        self.pushButton_2.setText(_translate("Form", "设置下课/用餐时间"))
        self.pushButton_3.setText(_translate("Form", "实验性选项/关于"))
        self.checkBox_6.setText(_translate("Form", "自动查杀PowerPoint"))
        self.checkBox_8.setText(_translate("Form", "自动查杀希沃白板"))
        self.checkBox_7.setText(_translate("Form", "自动查杀希沃展台"))
        self.checkBox_11.setText(_translate("Form", "自动查杀指定的程序"))
        self.checkBox_5.setText(_translate("Form", "满足下列条件时执行强制措施"))
        self.checkBox_9.setText(_translate("Form", "拖堂超过秒数"))
        self.checkBox_10.setText(_translate("Form", "下课后是用餐时间（敬请期待）"))
        self.radioButton.setText(_translate("Form", "与"))
        self.radioButton_2.setText(_translate("Form", "或"))
        self.radioButton_3.setText(_translate("Form", "非"))
        self.lineEdit.setText(_translate("Form", "300"))
        self.lineEdit_2.setText(_translate("Form", "30"))
        self.label_4.setText(
            _translate("Form", "<html><head/><body><p>无人值守倒计时</p></body></html>")
        )
        self.label_8.setText(_translate("Form", "窗口标题文本"))
        self.lineEdit_3.setText(_translate("Form", "30"))
        self.label_10.setText(_translate("Form", "提醒文本"))
        self.lineEdit_4.setText(_translate("Form", "30"))
        self.label_11.setText(_translate("Form", "拖堂选项文本"))
        self.lineEdit_6.setText(_translate("Form", "30"))
        self.label_12.setText(_translate("Form", "下课选项文本"))
        self.lineEdit_7.setText(_translate("Form", "30"))
        self.label_13.setText(_translate("Form", "信息框标题文本"))
        self.lineEdit_8.setText(_translate("Form", "30"))
        self.label_14.setText(_translate("Form", "拖堂信息"))
        self.lineEdit_9.setText(_translate("Form", "30"))
        self.label_15.setText(_translate("Form", "下课信息"))
        self.lineEdit_10.setText(_translate("Form", "30"))
        self.checkBox.setText(_translate("Form", "让ClassIsland接管下课事件"))
        self.label_16.setText(
            _translate(
                "Form",
                '<html><head/><body><p><span style=" font-weight:700; color:#ff0000;">危险！除非您明确下方各个选项的用途和后果，否则不要修改任意内容！</span></p></body></html>',
            )
        )
        self.label_17.setText(
            _translate(
                "Form",
                '<html><head/><body><p><span style=" font-size:14pt; font-weight:700;">Pandora Boxxx</span></p></body></html>',
            )
        )
        self.label_18.setText(
            _translate(
                "Form",
                '<html><head/><body><p><span style=" font-size:14pt; font-weight:700;">关于</span></p></body></html>',
            )
        )
        self.label_19.setText(
            _translate(
                "Form",
                '<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">\n'
                '<html><head><meta name="qrichtext" content="1" /><meta charset="utf-8" /><style type="text/css">\n'
                "p, li { white-space: pre-wrap; }\n"
                "hr { height: 1px; border-width: 0; }\n"
                'li.unchecked::marker { content: "\\2610"; }\n'
                'li.checked::marker { content: "\\2612"; }\n'
                "</style></head><body style=\" font-family:'Tahoma'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
                '<p style=" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><span style=" color:#000000;">程序作者：xxt8582753</span></p>\n'
                '<p style=" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><span style=" color:#000000;">网站：</span><a href="https://xxtsoft.top"><span style=" text-decoration: underline; color:#0000ff;">https://xxtsoft.top</span></a></p>\n'
                '<p style=" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><span style=" color:#000000;">邮箱：</span><a href="mailto:xxt8582753@126.com"><span style=" text-decoration: underline; color:#0000ff;">xxt8582753@126.com</span></a></p></body></html>',
            )
        )
        self.pushButton_5.setText(_translate("Form", "编辑JSON"))
        self.label_21.setText(
            _translate(
                "Form",
                '<html><head/><body><p><span style=" font-size:14pt; font-weight:700;">下课时间编辑器</span></p></body></html>',
            )
        )
        self.label_20.setText(
            _translate(
                "Form",
                "<html><head/><body><p>输入24小时制下课时间，默认00:00:00留空（应该没有学校这个点下课吧）</p><p>提示：可以按Tab切换焦点</p></body></html>",
            )
        )
        self.timeEdit.setDisplayFormat(_translate("Form", "HH:mm:ss"))
        self.timeEdit_2.setDisplayFormat(_translate("Form", "HH:mm:ss"))
        self.timeEdit_3.setDisplayFormat(_translate("Form", "HH:mm:ss"))
        self.timeEdit_4.setDisplayFormat(_translate("Form", "HH:mm:ss"))
        self.timeEdit_5.setDisplayFormat(_translate("Form", "HH:mm:ss"))
        self.timeEdit_6.setDisplayFormat(_translate("Form", "HH:mm:ss"))
        self.timeEdit_7.setDisplayFormat(_translate("Form", "HH:mm:ss"))
        self.timeEdit_8.setDisplayFormat(_translate("Form", "HH:mm:ss"))
        self.timeEdit_9.setDisplayFormat(_translate("Form", "HH:mm:ss"))
        self.timeEdit_10.setDisplayFormat(_translate("Form", "HH:mm:ss"))
        self.timeEdit_11.setDisplayFormat(_translate("Form", "HH:mm:ss"))
        self.timeEdit_12.setDisplayFormat(_translate("Form", "HH:mm:ss"))
        self.label_23.setText(_translate("Form", "设置保存成功"))
